version: '3.9'

services:
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ../envs/common-smart-contract-verifier.env
    environment:
      SMART_CONTRACT_VERIFIER__SOLIDITY__COMPILERS_DIR:
      SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: 'https://solc-bin.ethereum.org/linux-amd64/list.json'
      SMART_CONTRACT_VERIFIER__VYPER__FETCHER__LIST__LIST_URL: 'https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json'